
"""Static K-Field definitions for Q-DAS ASCII Transfer Format V12.

Replaces the ``qdas.toml`` data with typed Python structures so the
TOML parse overhead is eliminated and IDEs can introspect field metadata.

Three registries are exported:

- :data:`REQUIRED` — ``{key: name}`` for the five mandatory header fields.
- :data:`DEFINED`  — ``{key: FieldDef}`` for fields whose coded integer
  values have human-readable labels.
- :data:`SUPPORTED` — ``{key: name}`` for all documented but non-coded
  fields.
- :data:`CATALOG`   — ``{key: name}`` for catalog K-Fields (K4xxx).
"""

from types import MappingProxyType
from typing import Mapping, NamedTuple

__all__ = [
    'FieldDef',
    'REQUIRED',
    'DEFINED',
    'SUPPORTED',
    'CATALOG',
]


class FieldDef(NamedTuple):
    """Definition of a K-Field with coded integer values.

    Parameters
    ----------
    name : str
        Human-readable field name (e.g. ``'Merkmalart'``).
    values : Mapping[int, str]
        Mapping of raw integer codes to their label strings.
    comments : Mapping[int, str], optional
        Optional version or annotation comments keyed by code.
    """
    name: str
    values: Mapping[int, str] = MappingProxyType({})
    comments: Mapping[int, str] = MappingProxyType({})


# ---------------------------------------------------------------------------
# Shared value maps — defined once, referenced by multiple K-Fields
# ---------------------------------------------------------------------------

_ANKREUZFELDER = MappingProxyType({
    0: 'nicht angekreuzt',
    1: 'angekreuzt',
})

_DOKUMENTATIONSPFLICHT = MappingProxyType({
    0: 'Nein',
    1: 'Ja / DmbA - Teil/Merkmal',
    2: 'S-Teil/Merkmal',
    3: 'R-Teil/Merkmal',
    4: 'R&S-Teil/Merkmal',
    5: 'A-Teil/Merkmal',
    6: 'B-Teil/Merkmal',
    10: 'Besonderes Teil/Merkmal',
    11: 'Besonderes Teil/Merkmal BP 1',
    12: 'Besonderes Teil/Merkmal BP 2',
    13: 'Besonderes Teil/Merkmal BP 1 SPC',
    14: 'Besonderes Teil/Merkmal BP 2 SPC',
    15: 'R1',
    16: 'R2',
    17: 1,
    18: 2,
    19: 3,
    20: 4,
    22: 'Dokupflicht sicherheitsrelevant',
    23: 'Dokupflicht zertifizierungsrelevant',
    24: 'Produktionstelevant (keine Dokupflicht)',
    25: 'Fertigungsrelevant (keine Dokupflicht)',
    26: 'Besonderes Teil/Merkmal F',
    27: 'Besonderes Teil/Merkmal L/CoP',
    28: 'Besonderes Teil/Merkmal S',
})

_PRUEFUNGSARTEN = MappingProxyType({
    1: 'Funktionsprüfung',
    2: 'Maßprüfung',
    3: 'Werkstoffprüfung',
    4: 'Zuverlässigkeitsprüfung',
    5: 'Prozessfähigkeitsnachweis',
    6: 'Prozessablaufdiagramm',
    7: 'Prüfmittelfähigkeitsnachweis',
    8: 'Prüfmittelliste',
    9: 'EG-Datensicherheitsblatt',
    10: 'Haptik',
    11: 'Akustik',
    12: 'Geruch',
    13: 'Erscheinungsbild',
    14: 'Zertifikate',
    15: 'Konstruktionsfreigabe',
    16: 'Inhaltsstoffe in Zukaufteilen',
    17: 'Sonstiges',
    18: 'Werkstoff- und Funktionsprüfung',
})

_GESAMTENTSCHEID = MappingProxyType({
    1: 'freigegeben',
    2: 'freigegeben mit Auflage',
    3: 'abgelehnt, neue Muster erforderlich',
    4: 'abgelehnt, mit Maßnahmen verbaubar',
    5: 'abgelehnt',
    6: 'andere',
})

_ART_DER_GRENZE = MappingProxyType({
    0: 'keine Grenze',
    1: 'Grenzwert',
    2: 'natürliche Grenze',
})


# ---------------------------------------------------------------------------
# REQUIRED — mandatory header fields
# ---------------------------------------------------------------------------

REQUIRED: Mapping[str, str] = MappingProxyType({
    'K0100': 'Merkmalanzahl',
    'K1001': 'Teilenummer',
    'K1002': 'Teilebezeichnung',
    'K2001': 'Merkmalnummer',
    'K2002': 'Merkmalname',
})


# ---------------------------------------------------------------------------
# DEFINED — fields with coded integer → label mappings
# ---------------------------------------------------------------------------

DEFINED: Mapping[str, FieldDef] = MappingProxyType({
    'K0015': FieldDef('Untersuchungszweck', MappingProxyType({
        0: 'Laufende Messung',
        10: 'Sondermessung',
        20: 'Auditmessung',
    })),
    'K1010': FieldDef('Dokumentationspflicht', _DOKUMENTATIONSPFLICHT),
    'K1015': FieldDef('Untersuchungsart', MappingProxyType({
        1: 'Zuverlässigkeitsanalyse',
        10: 'Stichprobenanalyse',
        20: 'Prozessanalyse',
        30: 'Messsystemanalyse',
        50: 'Regressions-/Varianzanalyse',
        60: 'Erstmusterprüfbericht',
    })),
    'K1017': FieldDef('Prüfplanstatus', MappingProxyType({
        0: 'Frei',
        1: 'Gesperrt',
        2: 'Abgeschlossen',
        3: 'Bewertet',
    })),
    'K2004': FieldDef('Merkmalart', MappingProxyType({
        0: 'variabel',
        1: 'attributiv',
        2: 'variabel-klassiert',
        3: 'ordinal',
        4: 'nominal',
        5: 'Fehlerart',
        6: 'Fehlersammelkarte',
    })),
    'K2005': FieldDef('Merkmalklasse', MappingProxyType({
        0: 'unwichtig',
        1: 'wenig wichtig',
        2: 'wichtig',
        3: 'signifikant',
        4: 'kritisch',
    })),
    'K2006': FieldDef('Dokumentationspflicht', _DOKUMENTATIONSPFLICHT),
    'K2007': FieldDef('Regelungsart', MappingProxyType({
        0: 'keine Regelung',
        1: 'abhängig mitgeregelt',
        2: 'manuell',
        3: 'automatische Regelung',
    })),
    'K2008': FieldDef('Gruppentyp', MappingProxyType({
        0: 'keine Gruppe / Koordinate',
        1: 'logische Gruppe',
        2: 'Positionstoleranz',
        5: 'Aufteilung (nach Zusatzdaten)',
        6: 'Fehlersammelkarte',
        8: 'Best-Fit-Move Gruppe',
        9: 'Oberflächenstudie',
        10: '3D-Positionstoleranz',
        11: 'AFNOR E60-181 max/min',
        12: 'MMC (Bohrung)',
        13: 'MMC (Welle)',
        14: 'VDA 5 neu',
    })),
    'K2009': FieldDef('Messgrösse', MappingProxyType({
        0: 'undefiniert',
        100: 'Geradheit',
        101: 'Ebenheit',
        102: 'Rundheit',
        103: 'Zylinderform',
        104: 'Linienform',
        105: 'Flächenform',
        106: 'Neigung',
        107: 'Rechtwinkligkeit',
        108: 'Parallelität',
        109: 'Position (Betrag)',
        110: 'Konzentrizität',
        111: 'Symmetrie',
        112: 'Rundlauf',
        113: 'Gesamtlauf',
        114: 'CompCoaxial',
        115: 'CompPattern',
        117: 'Koordinaten',
        118: 'Planlauf',
        120: 'X-Koordinate',
        121: 'Y-Koordinate',
        122: 'Z-Koordinate',
        125: 'Versatz',
        132: 'Ovalität',
        140: 'Bewertungszahl Winkelfläche',
        145: 'Oberflächenbearbeitung',
        149: 'Freilegetiefe',
        150: 'Rauhtiefe Rz',
        151: 'Höhe Profil Rt=Pt',
        152: 'Mittelw. Profilordinate Ra',
        153: 'Profiltiefe Pt',
        154: 'Kernrauhtiefe Rk',
        155: 'Red. Spitzenhöhe',
        156: 'Red. Riefentiefe',
        157: 'Rauhigkeit Wt',
        158: 'Maximale Rauhtiefe',
        159: 'Grundrauhtiefe',
        160: 'Materialanteil Pmr',
        161: 'Materialanteil Mr1',
        162: 'Materialanteil Mr2',
        170: 'Dralltiefe',
        171: 'Drallwinkel',
        172: 'Drallsteigung',
        180: 'mittlere dominante Welligkeit',
        181: 'max. dominante Welligkeit',
        182: 'Länge der dominanten Welligkeit',
        190: 'Mittl. Tiefe d. Rauheitsmotifs',
        191: 'Max. Tiefe d. Profilunregelmäßigkeit',
        192: 'Mittl. Teilung d. Rauheitsmotifs',
        193: 'Materialanteil Rmr',
        194: 'Materialanteil tp',
        200: 'Längenmaß',
        201: 'Radius',
        202: 'Durchmesser',
        203: 'Winkel',
        204: 'Ellipse kleiner Ø',
        205: 'Ellipse großer Ø',
        206: 'Kegelwinkel',
        207: 'Innendurchmesser',
        208: 'Außendurchmesser',
        210: 'Kugelmaß',
        211: 'Zahndicke / -höhe',
        212: 'Zahndicke auf dem Teilzylinder',
        214: 'Zahndickenabmaß (auf dem Teilzylinder)',
        215: 'Zahndickenschwankung',
        216: 'Zahnweite (über k Meßzähne oder Meßlücken)',
        220: 'Federrate',
        230: 'Breite',
        231: 'Rechtwinkligkeit mit 2 Bezugsachsen',
        232: 'Maximaler Durchmesser',
        233: 'Minimaler Durchmesser',
        234: 'Durchschnittlicher Durchmesser',
        250: 'Temperatur [°C]',
        251: 'Temperatur [F]',
        255: 'Druck [bar]',
        260: 'Schichtdicke',
        270: 'Volumen',
        280: 'Masse',
        282: 'Kraft',
        285: 'Härte',
        290: 'Viskosität',
        300: 'Unwucht',
        301: 'Drehmoment',
        302: 'Anzugsdrehmoment',
        303: 'Weiterdrehmoment',
        310: '2D Notiz',
        311: '3D Notiz',
        320: 'Drehwinkel',
        350: 'Drehzahl',
        360: 'Winkelfehler',
        362: 'Profilfehler',
        364: 'Geschwindigkeitsfehler',
        370: 'Formabweichung',
        372: 'Formzuwachs',
        380: 'Nockenhöhe',
        501: 'Widerstand',
        502: 'Kapazität',
        503: 'Induktivität',
        504: 'Phasenverschiebung',
        505: 'Frequenz',
        506: 'Stromstärke',
        507: 'Spannung',
        508: 'Leistung',
        509: 'Feldstärke',
        601: 'Teilung',
        602: 'Teilungssprung',
        604: 'Teilungs- Gesamtabweichung',
        605: 'Teilungs-Summenabweichung',
        606: 'Teilungsschwankung',
        607: 'Gesamtteilungsfehler',
        608: 'Eingriffteilungs-Abweichung',
        609: 'Axialteilungs-Abweichung',
        610: 'Kopfkreisdurchmesser',
        612: 'Fußkreisdurchmesser',
        617: 'Lückenweite auf dem Teilzylinder',
        620: 'Linie',
        621: 'Flankenlinien-Formabweichung',
        630: 'Profil',
        631: 'Profil-Formabweichung',
        632: 'Profil- Winkelabweichung',
        633: 'Profiltaumel',
        640: 'Kopfrücknahme',
        641: 'Profilballigkeit',
        642: 'Breitenballigkeit',
        643: 'Höhenballigkeit',
        651: 'Flankenlinien- Winkelabweichung',
        652: 'Flankenlinientaumel',
        660: 'Rundlaufabweichung',
        661: 'Außermittigkeit',
        662: 'Taumel',
        663: 'Koaxialität',
        670: 'Zweiflanken-Wälzabweichung',
        671: 'Zweiflanken-Wälzsprung',
        672: 'Wälzrundlaufabweichung',
        673: 'Diametrales Zweikugelmaß',
        674: 'Diametrales Zweirollenmaß',
        675: 'Radiales Einkugelmaß',
        676: 'Radiales Einrollenmaß',
        800: 'Zeit',
        805: 'Anzahl',
        820: 'Geräusch',
        910: 'Leckrate',
        950: 'Bauteilsauberkeit',
        955: 'Rest-Partikel',
    }), MappingProxyType({
        125: 'ab 10/130823',
        132: 'ab 10/130823',
        193: 'ab 10/130823',
        194: 'ab 10/130823',
        207: 'ab 10/130823',
        208: 'ab 10/130823',
        212: 'ab 10/130823',
        214: 'ab 10/130823',
        215: 'ab 10/130823',
        216: 'ab 10/130823',
        230: 'ab V11/150515',
        231: 'ab V11/150515',
        232: 'ab V11/150515',
        233: 'ab V11/150515',
        234: 'ab V11/150515',
        310: 'ab 10/130823',
        311: 'ab 10/130823',
        360: 'ab 10/130823',
        362: 'ab 10/130823',
        364: 'ab 10/130823',
        370: 'ab 10/130823',
        372: 'ab 10/130823',
        380: 'ab 10/130823',
        606: 'ab 10/130823',
        608: 'ab 10/130823',
        609: 'ab 10/130823',
        610: 'ab 10/130823',
        612: 'ab 10/130823',
        617: 'ab 10/130823',
        661: 'ab 10/130823',
        670: 'ab 10/130823',
        671: 'ab 10/130823',
        672: 'ab 10/130823',
        673: 'ab 10/130823',
        674: 'ab 10/130823',
        675: 'ab 10/130823',
        676: 'ab 10/130823',
        805: 'ab 10/130823',
        950: 'ab 10/130823',
        955: 'ab 10/130823',
    })),
    'K2011': FieldDef('Verteilungsart', MappingProxyType({
        1: 'Normalverteilung',
        2: 'Log. Normalverteilung',
        4: 'Wurzeltransformierte Normalverteilung',
        11: 'Betragsverteilung 1. Art [0]',
        12: 'Raleighverteilung/Betragsverteilung 2. Art [0]',
        21: 'Betragsverteilung 1. Art [<> 0]',
        22: 'Raleighverteilung/Betragsverteilung 2. Art [<> 0]',
        30: 'Weibullverteilung',
        91: 'Johnson-Transformation',
        92: 'Mischverteilung',
        99: 'Pearson-Verteilungssystem',
        100: 'Binomialverteilung',
        200: 'Poissonverteilung',
    })),
    'K2015': FieldDef('Art der Abnutzung', MappingProxyType({
        0: 'Undefiniert',
        1: 'Steigend',
        2: 'Fallend',
    })),
    'K2016': FieldDef('100% Messung', MappingProxyType({
        0: 'Nein',
        1: 'Ja',
    })),
    'K2017': FieldDef('Art der Alarmermittlung', MappingProxyType({
        0: 'Standard',
        1: 'Alarme immer ermitteln',
        2: 'Alarme nicht ermitteln',
    })),
    'K2018': FieldDef('Akzeptanzgrenzen erweitert', MappingProxyType({
        0: 'Nein',
        1: 'Ja',
    })),
    'K2080': FieldDef('Merkmalsstatus', MappingProxyType({
        0: 'Aktiviert',
        1: 'Deaktiviert',
        2: 'Merkmal von der Eingabe ausgeschlossen/Deaktiviert für die Auswertung im neuen VDA5*',
        4: 'Merkmal vom Upload ausschliessen',
        8: 'Messwerte vom Upload ausschliessen',
        128: 'Merkmal von der Punktbewertung ausschliessen',
    })),
    'K2120': FieldDef('Art der Grenze', _ART_DER_GRENZE),
    'K2121': FieldDef('Art der Grenze', _ART_DER_GRENZE),
    'K2202': FieldDef('Auswertetyp', MappingProxyType({
        1: 'Typ 1',
        2: 'Typ 2',
        3: 'Typ 3',
        4: 'Cnomo 1',
        5: 'Cnomo 2',
        42: 'Typ 4',
        51: 'Typ 5',
        52: 'Einflusskomponente mit Messwerten',
        55: 'Einflusskomponente',
        72: 'GM Typ 2',
        73: 'GM Typ 3',
        81: 'GM Typ 1A',
        92: 'Short Range',
        93: 'Stabilität',
        94: 'Linearität',
        95: 'Attributiv',
        98: 'Prüfsystem',
        99: 'Prüfprozess',
        100: 'Unsicherheitsstudie VDA/ISO',
        104: 'Wiederholbarkeit am Normal',
        108: 'Messwerte der Prüfobjekte',
    }), MappingProxyType({
        1: 'Einzelmerkmalsbetrachtung',
        2: 'Einzelmerkmalsbetrachtung',
        3: 'Einzelmerkmalsbetrachtung',
        4: 'Einzelmerkmalsbetrachtung',
        5: 'Einzelmerkmalsbetrachtung',
        42: 'Einzelmerkmalsbetrachtung',
        51: 'Einzelmerkmalsbetrachtung',
        52: 'Nur im VDA5 (neu) zu nutzen',
        55: 'Nur im VDA5 (neu) zu nutzen',
        72: 'Einzelmerkmalsbetrachtung',
        73: 'Einzelmerkmalsbetrachtung',
        81: 'Einzelmerkmalsbetrachtung',
        92: 'Einzelmerkmalsbetrachtung',
        93: 'Einzelmerkmalsbetrachtung',
        94: 'Einzelmerkmalsbetrachtung',
        95: 'Einzelmerkmalsbetrachtung',
        98: 'Nur im VDA5 (neu) zu nutzen',
        99: 'Nur im VDA5 (neu) zu nutzen',
        100: 'Nur im VDA5 (neu) zu nutzen',
        104: 'Nur im VDA5 (neu) zu nutzen',
        108: 'Nur im VDA5 (neu) zu nutzen',
    })),
    'K2430': FieldDef('Prüfungsarten', _PRUEFUNGSARTEN),
    'K2432': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K2434': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K2501': FieldDef('Bemassungsattribut', MappingProxyType({
        0: 'keine Angabe',
        1: 'Basisbemassung',
        2: 'Prüfbemassung',
    })),
    'K2502': FieldDef('Darstellungsformat Toleranz', MappingProxyType({
        0: 'Nominal (10 oder 10 H7)',
        1: 'Grenzen (Limits) (9,9-10,1)',
        2: 'plusminus (10 +/-0,1 Abmaß kann oben anders sein als unten, z. B. 10 +0.2 – 0,1)',
        3: 'PlusMinusSymbol (wie 2 Abmaß oben und unten gleich, z.B. 10 +/- 0.1)',
    })),
    'K2503': FieldDef('Bemassungstyp', MappingProxyType({
        0: 'undefiniert',
        1: 'Zeichnungsmass',
        2: 'Modellmass',
        3: 'Referenzmass',
    })),
    'K2504': FieldDef('Zeichnungsänderung Status', MappingProxyType({
        0: 'keine Änderung (im Vergleich zur letzten Zeichnung)',
        1: 'geändertes Merkmal (im Vergleich zur letzten Zeichnung)',
        2: 'neues Merkmal (im Vergleich zur letzten Zeichnung)',
        3: 'gelöschtes Merkmal',
    })),
    'K3020': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3021': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3022': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3030': FieldDef('Prüfungsarten', _PRUEFUNGSARTEN),
    'K3035': FieldDef('Bemusterungsgrund', MappingProxyType({
        1: 'Neuteil',
        2: 'Produktänderung',
        3: 'Produktionsverlagerung',
        4: 'Änderung von Produktionsverfahren',
        5: 'längeres Aussetzen der Fertigung',
        6: 'neuer Unterlieferant',
        7: 'Produkt mit DmbA',
        8: 'Fertigungs-/Prüfplan erstellt',
        9: 'FMEA durchgeführt',
        10: 'geänderte Spezifikation',
        11: 'geänderte Fertigungsbedingungen',
        12: 'Initial Submission',
        13: 'Tooling = Transfer, Replacement, Refurbishment or additional',
        14: 'Correction of Discrepancy',
        15: 'Change to Optional Construction or Material',
        16: 'Change in Part Processing',
        17: 'Other - please specify',
    })),
    'K3037': FieldDef('Submission Level', MappingProxyType({
        1: 'Level 1',
        2: 'Level 2',
        3: 'Level 3',
        4: 'Level 4',
        5: 'Level 5',
    })),
    'K3040': FieldDef('Art der ermittelten Prozessfähigkeit', MappingProxyType({
        1: 'voraussichtliche Prozessfähigkeit',
        2: 'vorläufige Prozessfähigkeit',
        3: 'Prozessfähigkeit in der Serie',
    })),
    'K3108': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3109': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3112': FieldDef('Durchgeführte Untersuchung', MappingProxyType({
        1: 'Überprüfte Zeichnungen',
        2: 'Materialprüfergebnisse',
        3: 'Kontrollplan',
        4: 'Zusätzliche Zeichnungen/Skizzen',
        5: 'Zertifikate',
        6: 'Prozessfähigkeits-Nachweise',
        7: 'Genaue Anzahl der Musterteile',
        8: 'Funktions (ES) Test-Ergebnisse',
        9: 'Fertigungsablauf-Diagramm',
        10: 'Dimensionelle Ergebnisse',
        11: 'Genehmigung der Produktentwicklung',
        12: 'Lehrenfähigkeits-Nachweise',
        13: 'FMEA',
        14: 'selbstzertifizierender Lieferant',
    })),
    'K3115': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3420': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3421': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3422': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3423': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3424': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3425': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3426': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3427': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3428': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3429': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3430': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3431': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3432': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3433': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3434': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3435': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3436': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3437': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3438': FieldDef('Gesamtentscheid und Entscheidungen zu Einzel-prüfungen', _GESAMTENTSCHEID),
    'K3440': FieldDef('Prüfungsarten', _PRUEFUNGSARTEN),
    'K3442': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3701': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3702': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3703': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3704': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3705': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3706': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3707': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3708': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3709': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3710': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3711': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3712': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3713': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3714': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3750': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3752': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3754': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3756': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3760': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K3763': FieldDef('Ankreuzfelder', _ANKREUZFELDER),
    'K8501': FieldDef('Stichprobenart', MappingProxyType({
        0: 'fest',
        1: 'gleitend',
        2: 'Pseudo-fest',
    })),
    'K8503': FieldDef('Stichprobenart attributiv', MappingProxyType({
        0: 'Variabel',
        1: 'Konstant',
        2: 'Einzelspeicherung',
    })),
    'K8530': FieldDef('Prozessstabilität', MappingProxyType({
        1: 'Stabil',
        2: 'nicht stabil',
    })),
})


# ---------------------------------------------------------------------------
# SUPPORTED — documented fields without coded values (name only)
# ---------------------------------------------------------------------------

SUPPORTED: Mapping[str, str] = MappingProxyType({
    'K0001': 'Werte',
    'K0002': 'Attribut',
    'K0004': 'Zeit/Datum',
    'K0005': 'Ereignisse',
    'K0006': 'Chargennummer / Identnummer',
    'K0007': 'Nestnummer / Spindelnummer',
    'K0008': 'Prüfer',
    'K0009': 'Text',
    'K0010': 'Maschine',
    'K0011': 'Prozessparameter',
    'K0012': 'Prüfmittel',
    'K0014': 'Teile Ident',
    'K0015': 'Untersuchungszweck',
    'K0016': 'Produktionsnummer',
    'K0017': 'Werkstückträgernummer',
    'K0020': 'Stichprobenumfang',
    'K0021': 'Anzahl Fehler',
    'K0053': 'Auftragsnummer',
    'K0054': 'K0054',
    'K0055': 'K0055',
    'K0056': 'K0056',
    'K0057': 'K0057',
    'K0058': 'K0058',
    'K0059': 'K0059',
    'K0060': 'K0060',
    'K0061': 'K0061',
    'K0062': 'K0062',
    'K0063': 'K0063',
    'K0080': 'Stichproben-Ident',
    'K0081': 'Messwertposition in der Stichprobe',
    'K0097': 'Werte GUID',
    'K0999': 'Anzahl Merkmale pro Teil = 0',
    'K0100': 'Gesamtanzahl Merkmale in der Datei',
    'K1001': 'Teil Nummer',
    'K1002': 'Teil Bezeichnung',
    'K1003': 'Teil Kurzbezeichnung',
    'K1004': 'Änderungsstand Teil',
    'K1005': 'Erzeugnis',
    'K1007': 'Teilenummer Kurzbezeichnung',
    'K1008': 'Teiletyp',
    'K1009': 'Teilecode',
    'K1010': 'Dokumentationspflicht',
    'K1011': 'Variante',
    'K1012': 'Sachnummer-Zusatz',
    'K1013': 'Sachnummer-Index',
    'K1014': 'Teileident',
    'K1015': 'Untersuchungsart',
    'K1016': 'Zusammenbauteil',
    'K1017': 'Prüfplanstatus',
    'K1020': 'Hersteller Katalog',
    'K1021': 'Hersteller Nummer Text',
    'K1022': 'Hersteller Name',
    'K1023': 'Hersteller Nummer',
    'K1030': 'Werkstoff Katalog',
    'K1031': 'Werkstoff Nummer Text',
    'K1032': 'Werkstoff Bezeichnung',
    'K1033': 'Werkstoff Nummer',
    'K1040': 'Zeichnung Katalog',
    'K1041': 'Zeichnung Nummer Text',
    'K1042': 'Zeichnung Änderung',
    'K1043': 'Zeichnung Index',
    'K1044': 'Zeichnung Nummer',
    'K1045': 'Zeichnungsgültigkeitsdatum',
    'K1046': 'Zeichnungsname',
    'K1047': 'Grundzeichnung Nummer',
    'K1048': 'CAD Zeichnungsdateiname',
    'K1050': 'Auftraggeber Katalog',
    'K1051': 'Auftraggeber Nummer Text',
    'K1052': 'Auftraggeber Bezeichnung',
    'K1053': 'Auftrag',
    'K1054': 'Auftraggeber Nummer',
    'K1060': 'Kunden Katalog',
    'K1061': 'Kunde Nummer Text',
    'K1062': 'Kunde Bezeichnung',
    'K1063': 'Kunde Nummer',
    'K1070': 'Lieferanten Katalog',
    'K1071': 'Lieferant Nummer Text',
    'K1072': 'Lieferant Bezeichnung',
    'K1073': 'Lieferant Nummer',
    'K1080': 'Maschinen Katalog',
    'K1081': 'Maschine Nummer Text',
    'K1082': 'Maschine Bezeichnung',
    'K1083': 'Maschine Nummer',
    'K1085': 'Maschine Standort',
    'K1086': 'Arbeitsgang / Operation',
    'K1087': 'Arbeitsgang Bezeichnung',
    'K1091': 'Linien Nummer',
    'K1092': 'Linie Bezeichnung',
    'K1100': 'Bereich im Werk',
    'K1101': 'Abteilung',
    'K1102': 'Werkstatt',
    'K1103': 'Kostenstelle',
    'K1104': 'Schicht',
    'K1105': 'Werksbereich-Nummer',
    'K1106': 'Abteilungs-Nummer',
    'K1107': 'Werkstatt-Nummer',
    'K1108': 'Kostenstellen-Nummer',
    'K1110': 'Bestellnummer',
    'K1111': 'Wareneingangsnummer',
    'K1112': 'Würfel',
    'K1113': 'Position',
    'K1114': 'Vorrichtung',
    'K1115': 'Fertigungsdatum',
    'K1201': 'Prüfeinrichtung Nummer Text',
    'K1202': 'Prüfeinrichtung Bezeichnung',
    'K1203': 'Prüfgrund',
    'K1204': 'Prüfbeginn',
    'K1205': 'Prüfende',
    'K1206': 'Prüfplatz',
    'K1207': 'Prüfplanersteller',
    'K1208': 'Prüfeinrichtung Nummer',
    'K1209': 'Prüfart (Messkennzeichen)',
    'K1210': 'Messtyp',
    'K1211': 'Normalnummer (Text)',
    'K1212': 'Normalbezeichnung',
    'K1215': 'Normalnummer',
    'K1221': 'Prüfernummer (Text)',
    'K1222': 'Prüfername',
    'K1223': 'Prüfernummer',
    'K1230': 'Messraum',
    'K1231': 'Messprogrammnummer',
    'K1232': 'Messprogrammversion',
    'K1301': 'Mandant',
    'K1302': 'Prüflos',
    'K1303': 'Werk',
    'K1304': 'Werk-Nummer',
    'K1311': 'Fertigungsauftrag',
    'K1341': 'Prüfplannummer Text',
    'K1342': 'Prüfplanname',
    'K1343': 'Prüfplan Erstellungsdatum',
    'K1344': 'Prüfplan Ersteller',
    'K1350': 'Ausgabe-Berichtsdatei',
    'K1800': 'Benutzer Feldbezeichnung 1',
    'K1801': 'Benutzer Feldtyp 1',
    'K1802': 'Benutzer Feldinhalt 1',
    'K1810': 'Benutzer Feldbezeichnung 2',
    'K1811': 'Benutzer Feldtyp 2',
    'K1812': 'Benutzer Feldinhalt 2',
    'K1820': 'Benutzer Feldbezeichnung 3',
    'K1821': 'Benutzer Feldtyp 3',
    'K1822': 'Benutzer Feldinhalt 3',
    'K1830': 'Benutzer Feldbezeichnung 4',
    'K1831': 'Benutzer Feldtyp 4',
    'K1832': 'Benutzer Feldinhalt 4',
    'K1840': 'Benutzer Feldbezeichnung 5',
    'K1841': 'Benutzer Feldtyp 5',
    'K1842': 'Benutzer Feldinhalt 5',
    'K1850': 'Benutzer Feldbezeichnung 6',
    'K1851': 'Benutzer Feldtyp 6',
    'K1852': 'Benutzer Feldinhalt 6',
    'K1860': 'Benutzer Feldbezeichnung 7',
    'K1861': 'Benutzer Feldtyp 7',
    'K1862': 'Benutzer Feldinhalt 7',
    'K1870': 'Benutzer Feldbezeichnung 8',
    'K1871': 'Benutzer Feldtyp 8',
    'K1872': 'Benutzer Feldinhalt 8',
    'K1880': 'Benutzer Feldbezeichnung 9',
    'K1881': 'Benutzer Feldtyp 9',
    'K1882': 'Benutzer Feldinhalt 9',
    'K1890': 'Benutzer Feldbezeichnung 10',
    'K1891': 'Benutzer Feldtyp 10',
    'K1892': 'Benutzer Feldinhalt 10',
    'K1900': 'Bemerkung',
    'K1997': 'Teile GUID',
    'K1998': 'Interne Konfiguration der Teileebene (reserviert)',
    'K2001': 'Merkmal Nummer',
    'K2002': 'Merkmal Bezeichnung',
    'K2003': 'Merkmal Kurztext',
    'K2004': 'Merkmal Art',
    'K2005': 'Merkmal Klasse',
    'K2006': 'Dokumentationspflicht',
    'K2007': 'Regelungsart',
    'K2008': 'Gruppentyp',
    'K2009': 'Messgrösse',
    'K2011': 'gespeicherte Verteilung',
    'K2013': 'Klassenweite',
    'K2015': 'Art der Abnutzung (Trend)',
    'K2016': '100% Messung',
    'K2017': 'Art der Alarmermittlung',
    'K2018': 'Akzeptanzgrenzen erweitert',
    'K2019': 'Ordinalklassenkatalog',
    'K2021': 'Verknüpfungsstring',
    'K2022': 'Nachkommastellen',
    'K2023': 'Transformation Art',
    'K2024': 'Transformation Parameter a',
    'K2025': 'Transformation Parameter b',
    'K2026': 'Transformation Parameter c',
    'K2027': 'Transformation Parameter d',
    'K2028': 'natürliche Verteilung',
    'K2030': 'Gruppennummer / FSK-Nummer',
    'K2031': 'Gruppenelement Nummer / FSK Nummer bei Fehlerart einer FSK',
    'K2035': 'Kalibrierdatum',
    'K2041': 'Erfassungsart',
    'K2042': 'Erfassungsgerät Nummer',
    'K2043': 'Erfassungsgerät Name',
    'K2044': 'Erfassungsgerät Index',
    'K2045': 'Erfassung Kanal',
    'K2046': 'Messungsart',
    'K2047': 'Softwareanforderung Index',
    'K2048': 'Übernahmekanal',
    'K2049': 'Kanalinitialisierung-Index',
    'K2051': 'Schnittstelle',
    'K2052': 'Baudrate',
    'K2053': 'IRQ Nummer',
    'K2054': 'Parität',
    'K2055': 'Datenbits',
    'K2056': 'Stopbits',
    'K2060': 'Ereigniskatalog (Actioncode)',
    'K2061': 'Prozessparameterkatalog',
    'K2062': 'Nestkatalog',
    'K2063': 'Maschinenkatalog',
    'K2064': 'Prüfmittelkatalog',
    'K2065': 'Prüferkatalog',
    'K2066': 'Subkatalog K0061',
    'K2067': 'Subkatalog K0062',
    'K2068': 'Subkatalog K0063',
    'K2071': 'Additionskonstante',
    'K2072': 'Multiplikationsfaktor',
    'K2073': 'Mass des Einstellmeisters',
    'K2074': 'aktueller Offset für Einstellmessungen',
    'K2075': 'Verstärkungsfaktor für Einstellmessungen',
    'K2076': 'Datum der Einstellmessung',
    'K2080': 'Merkmalstatus (aktiviert, deaktiviert)',
    'K2091': 'Merkmalindex',
    'K2092': 'Merkmalstext',
    'K2093': 'Bearbeitungszustand',
    'K2095': 'ElementCode',
    'K2096': 'ElementIndex',
    'K2097': 'ElementText',
    'K2098': 'Elementadress',
    'K2100': 'Sollwert / Zielwert',
    'K2101': 'Nennmass',
    'K2102': 'Pmax',
    'K2103': 'Toleranzklasse',
    'K2104': 'Toleranzwert',
    'K2105': 'Teile i.O. bei Zensorisierung',
    'K2110': 'Untere Spezifikationsgrenze',
    'K2111': 'Obere Spezifikationsgrenze',
    'K2112': 'Unteres Abmass',
    'K2113': 'Oberer Abmass',
    'K2114': 'Untere Schrottgrenze',
    'K2115': 'Obere Schrottgrenze',
    'K2116': 'Untere Akzeptanzgrenze',
    'K2117': 'Obere Akzeptanzgrenze',
    'K2120': 'Art der Grenze unten',
    'K2121': 'Art der Grenze oben',
    'K2130': 'Plausibilitätsgrenze unten',
    'K2131': 'Plausibilitätsgrenze oben',
    'K2135': 'Klassengrenze unten',
    'K2136': 'Klassengrenze oben',
    'K2137': 'Anzahl Klassen',
    'K2138': 'Ursprung der Klassierung',
    'K2139': 'Ursprung des Klassierungsmodells',
    'K2141': 'Einheit',
    'K2142': 'Einheit Bezeichnung',
    'K2143': 'Einheit relativ',
    'K2144': 'Additionskonstante relativ',
    'K2145': 'Multiplikationsfaktor relativ',
    'K2146': 'Nachkommastellen relativ',
    'K2151': 'Toleranz (als Text)',
    'K2152': 'Berechnete Toleranz',
    'K2160': 'Losumfang',
    'K2161': 'Kosten Nacharbeit',
    'K2162': 'Kosten Ausschuss',
    'K2163': 'Fehlerkosten',
    'K2170': 'Zensorisierungszeitpunkt',
    'K2171': 'Extrapolation',
    'K2172': 'Erlaubte Ausfallrate',
    'K2173': 'Ausfallfreie Zeit',
    'K2174': 'Teile im Feld',
    'K2175': 'Bedingungen für Häufigkeitssummen',
    'K2176': 'Laufstreckenverteilung nach Eckel',
    'K2177': 'Laufzeit X1',
    'K2178': 'Laufzeit X2',
    'K2180': 'Weibull Parameter b',
    'K2181': 'Weibull Parameter T',
    'K2182': 'Summenwahrscheinlichkeit (B(x1))',
    'K2183': 'Summenwahrscheinlichkeit (B(x2))',
    'K2185': 'Anzahl der Teile im Feld (für Eckel Verfahren)',
    'K2186': 'Einsatzzeit der Teile im Feld (für Eckel Verfahren)',
    'K2201': 'Prozessstreuung',
    'K2202': 'Auswertetyp',
    'K2205': 'Anzahl Teile, Anzahl Normale',
    'K2206': 'Anzahl Vorrichtungen',
    'K2207': 'Anzahl Prüfintervalle',
    'K2210': 'Normal Katalog',
    'K2211': 'Normal Nummer Text',
    'K2212': 'Normal Bezeichnung',
    'K2213': 'Normal Istwert',
    'K2214': 'Normal Temperatur',
    'K2215': 'Normal Nummer',
    'K2216': 'Normal-Seriennummer',
    'K2217': 'Normalhersteller',
    'K2220': 'Anzahl Prüfer',
    'K2221': 'Anzahl Messungen',
    'K2222': 'Anzahl Referenzmessungen',
    'K2225': 'Ermittelter Cg Wert',
    'K2226': 'Ermittelter Cgk Wert',
    'K2227': 'Abweichung GC Typ3 GC Typ1',
    'K2228': 'Sg Typ 1 - Stabilität',
    'K2243': 'Zeichnung Dateiname',
    'K2244': 'Zeichnung Referenzpunkt X',
    'K2245': 'Zeichnung Referenzpunkt Y',
    'K2246': 'Zeichnung Referenzpunkt Z',
    'K2261': 'Referenzteil-Nummer',
    'K2262': 'Referenzteil-Bezeichnung',
    'K2263': 'Referenzteil-Istwert',
    'K2264': 'Referenzteil-Temperatur',
    'K2265': 'Referenzteil-Nummer (num)',
    'K2266': 'Referenzteil-Seriennummer',
    'K2281': 'Einstellteil-Nummer mitte',
    'K2282': 'Einstellteil-Bezeichnung mitte',
    'K2283': 'Einstellteil-Istwert mitte',
    'K2284': 'Einstellteil-Temperatur mitte',
    'K2285': 'Einstellteil-Nummer (num) mitte',
    'K2286': 'Einstellteil-Seriennummer mitte',
    'K2301': 'Maschine Nummer Text',
    'K2302': 'Maschine Bezeichnung',
    'K2303': 'Abteilung / Kostenstelle',
    'K2304': 'Standort',
    'K2305': 'Maschine Nummer',
    'K2306': 'Bereich im Werk',
    'K2307': 'PTM-Nummer',
    'K2311': 'Fertigungsart Text (Operation)',
    'K2312': 'Fertigungsart Bezeichnung',
    'K2313': 'Fertigungsart Nummer',
    'K2320': 'Auftrag Nummer',
    'K2321': 'Auftraggeber Nummer Text',
    'K2322': 'Auftraggeber Name',
    'K2323': 'Auftraggeber Nummer',
    'K2331': 'Werkstück Nummer Text',
    'K2332': 'Werkstück Bezeichnung',
    'K2333': 'Werkstück Nummer',
    'K2341': 'Prüfplannummer Text',
    'K2342': 'Prüfplanname',
    'K2343': 'Prüfplan Erstellungsdatum',
    'K2344': 'Prüfplan Ersteller',
    'K2401': 'Prüfmittel Nummer Text',
    'K2402': 'Prüfmittel Bezeichnung',
    'K2403': 'Prüfmittel Gruppe',
    'K2404': 'Prüfmittel Auflösung',
    'K2405': 'Prüfmittel Nummer',
    'K2406': 'Prüfmittelhersteller',
    'K2407': 'SPC-Gerät Nummer',
    'K2408': 'SPC-Gerät Bezeichnung',
    'K2409': 'SPC-Gerät Typ',
    'K2410': 'Prüfort',
    'K2411': 'Prüfbeginn',
    'K2412': 'Prüfende',
    'K2413': 'Prüfmittelgrafik',
    'K2415': 'Prüfmittel-Seriennummer',
    'K2416': 'Anzeigegerät',
    'K2421': 'Prüfer Nummer Text',
    'K2422': 'Prüfer Name',
    'K2423': 'Prüfer Nummer',
    'K2430': 'Bemusterungsart',
    'K2432': 'Einzelwertausgabe',
    'K2434': 'Prozessfähigkeitsnachweis',
    'K2436': 'Test Frequency',
    'K2438': 'Quantity Tested',
    'K2440': 'ZSB-Komponente',
    'K2442': 'Masse der ZSB-Komponente',
    'K2444': 'Material der ZSB-Komponente',
    'K2446': 'Herstellerbezogene Produktbezeichnung',
    'K2448': 'Hersteller der ZSB-Komponente',
    'K2501': 'Bemassungsattribut',
    'K2502': 'Darstellungsformat Toleranz',
    'K2503': 'Bemassungstyp',
    'K2504': 'Zeichnungsänderung Status',
    'K2505': 'Ansichtsname',
    'K2506': 'Blattnummer',
    'K2507': 'Feldbuchstabe Zeichnung',
    'K2508': 'Feldzahl Zeichnung',
    'K2509': 'Blattbezeichnung',
    'K2511': 'Bezug 1',
    'K2512': 'Bezug 2',
    'K2513': 'Bezug 3',
    'K2514': 'Bezug 4',
    'K2515': 'Bezug 5',
    'K2516': 'Bezug 6',
    'K2517': 'Bezug 7',
    'K2518': 'Bezug 8',
    'K2519': 'Bezug 9',
    'K2520': 'Bezugssystem',
    'K2521': 'Bezug X-Richtung',
    'K2522': 'Bezug Y-Richtung',
    'K2523': 'Bezug Z-Richtung',
    'K2524': 'CAD interner Bezug',
    'K2525': 'RotationsMatrix',
    'K2526': 'CAD-Ausschnitt',
    'K2630': 'Kalibrierunsicherheit',
    'K2646': 'Komponentenart',
    'K2654': 'VDA 5 Version',
    'K2800': 'Benutzer Feldbezeichnung 1',
    'K2801': 'Benutzer Feldtyp 1',
    'K2802': 'Benutzer Feldinhalt 1',
    'K2810': 'Benutzer Feldbezeichnung 2',
    'K2811': 'Benutzer Feldtyp 2',
    'K2812': 'Benutzer Feldinhalt 2',
    'K2820': 'Benutzer Feldbezeichnung 3',
    'K2821': 'Benutzer Feldtyp 3',
    'K2822': 'Benutzer Feldinhalt 3',
    'K2830': 'Benutzer Feldbezeichnung 4',
    'K2831': 'Benutzer Feldtyp 4',
    'K2832': 'Benutzer Feldinhalt 4',
    'K2840': 'Benutzer Feldbezeichnung 5',
    'K2841': 'Benutzer Feldtyp 5',
    'K2842': 'Benutzer Feldinhalt 5',
    'K2850': 'Benutzer Feldbezeichnung 6',
    'K2851': 'Benutzer Feldtyp 6',
    'K2852': 'Benutzer Feldinhalt 6',
    'K2860': 'Benutzer Feldbezeichnung 7',
    'K2861': 'Benutzer Feldtyp 7',
    'K2862': 'Benutzer Feldinhalt 7',
    'K2870': 'Benutzer Feldbezeichnung 8',
    'K2871': 'Benutzer Feldtyp 8',
    'K2872': 'Benutzer Feldinhalt 8',
    'K2880': 'Benutzer Feldbezeichnung 9',
    'K2881': 'Benutzer Feldtyp 9',
    'K2882': 'Benutzer Feldinhalt 9',
    'K2890': 'Benutzer Feldbezeichnung 10',
    'K2891': 'Benutzer Feldtyp 10',
    'K2892': 'Benutzer Feldinhalt 10',
    'K2900': 'Bemerkung',
    'K2901': 'Prüfbedingungen',
    'K2997': 'Merkmal GUID',
    'K2998': 'interne Konfiguration',
    'K2999': 'interne qs-STAT Konfiguration',
    'K3001': 'Prüfbericht Nummer Lieferant',
    'K3002': 'Prüfbericht Bezeichnung Lieferant',
    'K3003': 'Kenn-Nummer Lieferant',
    'K3004': 'Prüfbericht Version Lieferant',
    'K3005': 'Prüfbericht Ausfertigung (Lieferant)',
    'K3006': 'Zeichen Lieferant',
    'K3010': 'Lieferant Nummer',
    'K3011': 'Lieferanten-Nummer',
    'K3020': 'Erstbemusterung',
    'K3021': 'Nachbemusterung',
    'K3022': 'Sonstige Muster',
    'K3023': 'Sonstige Muster Text',
    'K3025': 'Wiederholte Vorstellung Nummer',
    'K3030': 'Anlagen (Prüfungsarten)',
    'K3031': 'Andere Anlagen (Prüfungsarten)',
    'K3035': 'Bemusterungsgrund',
    'K3036': 'other - please specify',
    'K3037': 'Requested submission level',
    'K3040': 'Prozessfähigkeit',
    'K3050': 'Sachnummer Lieferant',
    'K3052': 'Benennung Lieferant',
    'K3055': 'Zeichnungsnummer Lieferant',
    'K3056': 'Stand Lieferant',
    'K3057': 'Datum Lieferant',
    'K3058': 'Änderungsnummer Lieferant',
    'K3070': 'Bestellnummer Lieferant',
    'K3071': 'Abrufnummer Lieferant',
    'K3077': 'Bestelldatum Lieferant',
    'K3078': 'Abrufdatum Lieferant',
    'K3080': 'Lieferschein-Nummer Lieferant',
    'K3087': 'Lieferschein-Datum Lieferant',
    'K3100': 'Artikelnummer',
    'K3101': 'Liefermenge',
    'K3102': 'Liefereinheit',
    'K3103': 'Anzahl Muster',
    'K3105': 'Chargennummer',
    'K3106': 'Nestnummer',
    'K3107': 'Werkzeugnummer',
    'K3108': 'Restricted Substances',
    'K3109': 'Plastic Parts',
    'K3110': 'Mustergewicht (Lieferant)',
    'K3112': 'durchgeführt',
    'K3113': 'Application',
    'K3115': 'Dokumentationspflicht',
    'K3117': 'Checking Aid No.',
    'K3118': 'Change Level (Checking Aid No.)',
    'K3119': 'Date (Checking Aid No.)',
    'K3150': 'Ersteller (Lieferant)',
    'K3160': 'Unterschrift Ersteller',
    'K3167': 'Datum Erstellersignatur',
    'K3180': 'Spezifikationsunterlagen',
    'K3186': 'Production rate tkmebase (hours)',
    'K3187': 'Production rate / 8 hours',
    'K3188': 'Mold / Cav. / Prod.',
    'K3190': 'Bemerkung Lieferant',
    'K3200': 'Fertigungsauftragsnummer',
    'K3210': 'Prüfauftragsnummer',
    'K3281': 'Bemerkung Funktionsprüfung',
    'K3282': 'Bemerkung Massprüfung',
    'K3283': 'Bemerkung Werkstoffprüfung',
    'K3284': 'Bemerkung Zuverlässigkeitsprüfung',
    'K3285': 'Bemerkung Prozessfähigkeitsnachweis',
    'K3293': 'Bemerkung Erscheinungsbild',
    'K3296': 'Bemerkung Inhaltsstoffe',
    'K3298': 'Bemerkung Attributivprüfung',
    'K3301': 'Prüfbericht Nummer Abnehmer',
    'K3302': 'Prüfbericht Bezeichnung Abnehmer',
    'K3303': 'Kenn-Nummer Abnehmer',
    'K3304': 'Prüfbericht Version Abnehmer',
    'K3306': 'Zeichen Abnehmer',
    'K3310': 'Kundennummer',
    'K3350': 'Sachnummer Abnehmer',
    'K3352': 'Benennung Abnehmer',
    'K3355': 'Zeichnungsnummer Abnehmer',
    'K3356': 'Stand Abnehmer',
    'K3357': 'Datum Abnahme',
    'K3358': 'Änderungsnummer Abnehmer',
    'K3372': 'Wareneingangsnummer',
    'K3379': 'Wareneingangsdatum',
    'K3380': 'Lieferscheinnummer Abnehmer',
    'K3387': 'Lieferscheindatum Abnehmer',
    'K3390': 'Abladestelle',
    'K3404': 'Abnahmeverfahren',
    'K3410': 'Mustergewicht Abnehmer',
    'K3420': 'Gesamtentscheid',
    'K3421': 'Entscheidung Funktionsprüfung',
    'K3422': 'Entscheidung Massprüfung',
    'K3423': 'Entscheidung Werkstoffprüfung',
    'K3424': 'Entscheidung Zuverlässigkeit',
    'K3425': 'Entscheidung Prozessfähigkeit',
    'K3433': 'Entscheidung Sichtprüfung',
    'K3436': 'Entscheidung Inhaltsstoffe',
    'K3438': 'Entscheidung Attributivprüfung',
    'K3439': 'andere Entscheidung',
    'K3440': 'The Results for',
    'K3442': 'meet all drawing and specif. requmts.',
    'K3445': 'Abweich-Genehmigungsnummer',
    'K3447': 'Date (Additional Engineering Changes)',
    'K3450': 'Prüfbericht Ersteller (Abnehmer)',
    'K3451': 'Name Abnehmer',
    'K3460': 'Unterschrift Abnehmer',
    'K3467': 'Signaturdatum Abnehmer',
    'K3470': 'Einkäufer',
    'K3481': 'Auflagen',
    'K3490': 'Bemerkung Abnehmer',
    'K3560': 'Name of inspection facility',
    'K3561': 'Functional inspection facility',
    'K3562': 'Dimensional inspection facility',
    'K3563': 'Material inspection facility',
    'K3564': 'Zuverlässigkeit inspection facility',
    'K3565': 'Sichtprüfung inspection facility',
    'K3566': 'Attributivprüfung inspection facility',
    'K3569': 'Sonstige Prüfung inspection facility',
    'K3581': 'Bemerkung Funktionsprüfung (Abnehmer)',
    'K3582': 'Bemerkung Massprüfung (Abnehmer)',
    'K3583': 'Bemerkung Werkstoffprüfung (Abnehmer)',
    'K3600': 'Prüfbericht Art',
    'K3601': 'Prüfbericht Name/Beschreibung',
    'K3602': 'Eingabe-Maskendatei',
    'K3610': 'Änderer',
    'K3617': 'Änderungsdatum',
    'K3650': 'Bearbeitungszustand des Erstmusterprüfberichts',
    'K3701': 'Verteiler 1',
    'K3702': 'Verteiler 2',
    'K3703': 'Verteiler 3',
    'K3704': 'Verteiler 4',
    'K3705': 'Verteiler 5',
    'K3706': 'Verteiler 6',
    'K3707': 'Verteiler 7',
    'K3708': 'Verteiler 8',
    'K3709': 'Verteiler 9',
    'K3710': 'Verteiler 10',
    'K3711': 'Verteiler 11',
    'K3712': 'Verteiler 12',
    'K3713': 'Verteiler 13',
    'K3714': 'Verteiler 14',
    'K3750': 'Gefährliche Stoffe nach ChemG/GefStoffV?',
    'K3752': 'Entstehung von Gefahrstoffen bei sachgemässem Umgang?',
    'K3754': 'Gefahrgut nach Verkehrsrecht',
    'K3756': 'Wassergefährdende Stoffe nach Wasserrecht',
    'K3757': 'Wassergefährdungsklasse',
    'K3758': 'Menge wassergefährdender Stoffe',
    'K3760': 'Bauteil mit Bioziden',
    'K3761': 'Gehalt an Bioziden',
    'K3763': 'Entsteht bei Entsorgung ein Abfall mit EAK-Code?',
    'K3764': 'EAK-Code',
    'K3780': 'Zeichnungsname 2',
    'K3781': 'Zeichnungsname 3',
    'K3782': 'Zeichnungsname 4',
    'K5001': 'Gruppennummer (Text)',
    'K5002': 'Gruppenbezeichnung',
    'K5003': 'Gruppenkurzbezeichnung',
    'K5007': 'Gruppennummer-Kurzbezeichnung',
    'K5045': 'Skizze (Dateiname)',
    'K5090': 'Bemerkung',
    'K5098': 'interne qs-STAT Konfiguration',
    'K5101': 'Teil als Bestandteil einer Gruppe',
    'K5102': 'Merkmal als Bestandteil einer Gruppe',
    'K5103': 'Gruppe als Bestandteil einer Gruppe',
    'K5111': 'Teilegruppe',
    'K5112': 'Merkmalsgruppe',
    'K5113': 'Gruppenelement',
    'K8006': 'Untere Alarmgrenze (Lage)',
    'K8007': 'Obere Alarmgrenze (Lage)',
    'K8010': 'Kartenart und Zusatzattribute (Lage)',
    'K8011': 'Mittellage (Lage)',
    'K8012': 'untere Eingriffsgrenze UEG (Lage)',
    'K8013': 'obere Eingriffsgrenze OEG (Lage)',
    'K8014': 'untere Warngrenze UWG (Lage)',
    'K8015': 'obere Warngrenze OWG (Lage)',
    'K8106': 'Untere Alarmgrenze (Streuung)',
    'K8107': 'Obere Alarmgrenze (Streuung)',
    'K8110': 'Kartenart und Zusatzattribute (Streuung)',
    'K8111': 'Mittellage (Streuung)',
    'K8112': 'untere Eingriffsgrenze UEG (Streuung)',
    'K8113': 'obere Eingriffsgrenze OEG (Streuung)',
    'K8114': 'untere Warngrenze UWG (Streuung)',
    'K8115': 'obere Warngrenze OWG (Streuung)',
    'K8500': 'Stichprobe Umfang (gesamt)',
    'K8501': 'Stichprobe Art',
    'K8502': 'Stichprobe Frequenz',
    'K8503': 'Stichprobenart attributiv',
    'K8504': 'Stichprobenhäufigkeit',
    'K8505': 'Anzahl Teile (attr.)',
    'K8520': 'Geforderter Cp-Wert / Eignungsgrenzwert in %',
    'K8521': 'Geforderter Cpk-Wert',
    'K8522': 'Gefixter Cp-Wert',
    'K8523': 'Gefixter Cpk-Wert',
    'K8524': 'Geforderter CAM-Wert',
    'K8525': 'Geforderter nicht kritischer Fähigkeitsindex',
    'K8530': 'Prozessstabilität',
    'K8531': 'Eingegebene Prozessfähigkeit (Cp)',
    'K8532': 'Eingegebene Prozessfähigkeit (Cpk)',
    'K8540': 'Bewertung',
    'K8600': 'Korrekturstrategie',
    'K8610': 'untere Korrekturgrenze',
    'K8611': 'obere Korrekturgrenze',
    'K8612': 'Puffergrösse',
    'K8613': 'Korrekturzielwert',
})


# ---------------------------------------------------------------------------
# CATALOG — catalog K-Fields (K4xxx) — name only
# ---------------------------------------------------------------------------

CATALOG: Mapping[str, str] = MappingProxyType({
    'K4000': 'Kundenkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4001': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4002': 'Kunde_Nummer',
    'K4003': 'Kunde_Name 1',
    'K4004': 'Kunde_Name 2',
    'K4005': 'Kunde_Abteilung',
    'K4006': 'Kunde_Werk',
    'K4007': 'Kunde_Strasse-Postfach',
    'K4008': 'Kunde_Postleitzahl-Ort',
    'K4009': 'Kunde_Land',
    'K4010': 'Herstellerkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4011': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4012': 'Hersteller_Nummer',
    'K4013': 'Hersteller_Name 1',
    'K4014': 'Hersteller_Name 2',
    'K4015': 'Hersteller_Abteilung',
    'K4016': 'Hersteller_Werk',
    'K4017': 'Hersteller_Strasse-Postfach',
    'K4018': 'Hersteller_Postleizahl-Ort',
    'K4019': 'Hersteller_Land',
    'K4020': 'Lieferantenkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4021': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4022': 'Lieferant_Nummer',
    'K4023': 'Lieferant_Name 1',
    'K4024': 'Lieferant_Name 2',
    'K4025': 'Lieferant_Abteilung',
    'K4026': 'Lieferant_Werk',
    'K4027': 'Lieferant_Strasse-Postfach',
    'K4028': 'Lieferant_Postleitzahl-Ort',
    'K4029': 'Lieferant_Land',
    'K4030': 'Auftragskatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4031': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4032': 'Auftrag_Nummer',
    'K4033': 'Auftrag_Bezeichnung',
    'K4040': 'Werkstoffkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4041': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4042': 'Werkstoff_Nummer',
    'K4043': 'Werkstoff_Bezeichnung',
    'K4050': 'Zeichnungskatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4051': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4052': 'Zeichnung_Nummer',
    'K4053': 'Zeichnung_Änderung',
    'K4060': 'Maschinenkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4061': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4062': 'Maschine_Nummer',
    'K4063': 'Maschine_Bezeichnung',
    'K4064': 'Bereich',
    'K4065': 'Abteilung',
    'K4066': 'Arbeitsgang-Nr.',
    'K4067': 'Externe Referenznummer',
    'K4070': 'Prüfmittelkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4071': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4072': 'Prüfmittel_Nummer',
    'K4073': 'Prüfmittel_Bezeichnung',
    'K4074': 'Prüfmittel_Gruppe',
    'K4075': 'Prüfmittel_letzte-Prüfung',
    'K4076': 'Prüfmittel_nächste-Prüfung',
    'K4077': 'IP-Adresse',
    'K4078': 'Einsatzort',
    'K4079': 'Computermodell',
    'K4080': 'Einheitenkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4081': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4082': 'Einheit_Nummer',
    'K4083': 'Einheit_Bezeichnung',
    'K4090': 'Prüferkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4091': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4092': 'Prüfer_Nummer',
    'K4093': 'Prüfer_Name',
    'K4094': 'Prüfer_Abteilung',
    'K4095': 'Prüfer_Telefon',
    'K4096': 'Prüfer_Fax',
    'K4097': 'Prüfer_E-Mail',
    'K4098': 'Prüfer_Position',
    'K4099': 'Prüfer_Anrede',
    'K4100': 'Auftraggeberkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4101': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4102': 'Auftraggeber_Nummer',
    'K4103': 'Auftraggeber_Name',
    'K4110': 'Erzeugniskatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4111': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4112': 'Erzeugnis_Nummer',
    'K4113': 'Erzeugnis_Name',
    'K4120': 'Mitarbeiterkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4121': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4122': 'Mitarbeiter_Nummer',
    'K4123': 'Mitarbeiter_Name',
    'K4124': 'Mitarbeiter_Abteilung',
    'K4125': 'Mitarbeiter_Telefon',
    'K4126': 'Mitarbeiter_Fax',
    'K4127': 'Mitarbeiter_E-Mail',
    'K4128': 'Mitarbeiter_Position',
    'K4129': 'Mitarbeiter_Anrede',
    'K4220': 'Ereigniskatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4221': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4222': 'Ereignisnummer',
    'K4223': 'Ereignistext',
    'K4230': 'Ordinalklassenkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4231': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4232': 'Ordinalklassen_Nummer',
    'K4233': 'Ordinalklassen_Bezeichnung',
    'K4234': 'Ordinalklassen_Bewertung',
    'K4235': 'Ordinalklassen_Rang',
    'K4236': 'Ordinalklassen_i.O.-n.i.O.',
    'K4237': 'Ordinalklassen_Gültigkeit',
    'K4240': 'Prozessparameterkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4241': 'Katalogelement (Zuordnung Prozessparameter <-> Subkatalog)',
    'K4242': 'Nummer des Prozessparameters',
    'K4243': 'Bezeichnung des Prozessparameters',
    'K4244': 'Prozessparameterkurztext',
    'K4245': 'Prozessparameterwert_Nummer',
    'K4246': 'Prozessparameterwert_Text',
    'K4249': 'Zuordnung Prozessparameter <-> Prozessparameterwerte',
    'K4250': 'Nestkatalog (Bezeichnung des Haupt-/Subkatalogs)',
    'K4251': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4252': 'Nest_Nummer',
    'K4253': 'Nest_Bezeichnung',
    'K4270': 'Katalog K0061 (Bezeichnung des Haupt-/Subkatalogs)',
    'K4271': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4272': 'K0061_Nummer',
    'K4273': 'K0061_Bezeichnung',
    'K4280': 'Katalog K0062 (Bezeichnung des Haupt-/Subkatalogs)',
    'K4281': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4282': 'K0062_Nummer',
    'K4283': 'K0062_Bezeichnung',
    'K4290': 'Katalog K0063 (Bezeichnung des Haupt-/Subkatalogs)',
    'K4291': 'Zuordnung der Elemente des Hauptkatalogs zum jeweiligen Subkatalog',
    'K4292': 'K0063_Nummer',
    'K4293': 'K0063_Bezeichnung',
    'K4501': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4502': 'Kunde - Bemerkung',
    'K4511': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4512': 'Hersteller - Bemerkung',
    'K4521': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4522': 'Lieferant - Bemerkung',
    'K4531': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4532': 'Bemerkung',
    'K4541': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4542': 'Werkstoff - Bemerkung',
    'K4551': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4552': 'Bemerkung',
    'K4561': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4562': 'Bemerkung',
    'K4571': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4572': 'Bemerkung',
    'K4575': 'Programmversion',
    'K4576': 'Software',
    'K4581': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4582': 'Bemerkung',
    'K4591': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4592': 'Bemerkung',
    'K4601': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4602': 'Bemerkung',
    'K4611': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4612': 'Bemerkung',
    'K4621': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4622': 'Bemerkung',
    'K4721': 'Kennzeichnung spezieller Einträge',
    'K4722': 'Bemerkung',
    'K4731': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4732': 'Bemerkung',
    'K4741': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4742': 'Bemerkung',
    'K4751': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4752': 'Bemerkung',
    'K4771': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4772': 'Bemerkung',
    'K4781': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4782': 'Bemerkung',
    'K4791': 'Kennzeichnung nicht mehr genutzter Einträge',
    'K4792': 'Bemerkung',
})